version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 444397746555.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=444397746555.dkr.ecr.ap-northeast-1.amazonaws.com
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
      - IMAGE_NAME=handsonuser-ecsdemo-frontend

  build:
    commands:
      - docker build -t handsonuser-ecsdemo-frontend .
      - docker tag handsonuser-ecsdemo-frontend:latest 444397746555.dkr.ecr.ap-northeast-1.amazonaws.com/handsonuser-ecsdemo-frontend:${IMAGE_TAG}

  post_build:
    commands:
      - docker push 444397746555.dkr.ecr.ap-northeast-1.amazonaws.com/handsonuser-ecsdemo-frontend:latest
      - docker push 444397746555.dkr.ecr.ap-northeast-1.amazonaws.com/handsonuser-ecsdemo-frontend:${IMAGE_TAG}
      - printf '{"Version":"1.0","ImageURI":"%s"}' 444397746555.dkr.ecr.ap-northeast-1.amazonaws.com/handsonuser-ecsdemo-frontend:${IMAGE_TAG} > imageDetail.json

artifacts:
  files: imageDetail.json